# VOC & eCO2 sensor
sensor:
  - platform: sgp30
    eco2:
      name: "$deviceName eCO2"
      id: eco2
      accuracy_decimals: 1
    tvoc:
      name: "$deviceName TVOC"
      id: tvoc
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 60s
